# Generated by Django 2.0.7 on 2018-07-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180713_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='highlighted',
        ),
    ]
